### PR TITLE
updating olm config file with proper information

### PR DESCRIPTION
**Pull request by acornett21**
Issue #, if available:
N/A

Description of changes:
updating the olm config file so the CSV in the bundle has the proper information. Please let me know if this controller will have any more resources besides kind `Secret`

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by acornett21** [comment]
- Relates: k8s-operatorhub/community-operators#2987
- Relates: redhat-openshift-ecosystem/community-operators-prod#2942

**Comment by a-hilaly** [comment]
Errors are expected. I just wanted to double-check that. They will disappear once we merge the first CRD

**Comment by acornett21** [comment]
@a-hilaly This PR can follow the PR with the CRD(s).

**Pull request merged**
